[theme]
base="light"
primaryColor="#FF7F00"             # warna aksen tombol (opsional)
backgroundColor="#F0F0F0"          # background putih
secondaryBackgroundColor="#FFFFFF" # sidebar abu-abu terang
textColor="#000000"                # teks hitam
font="sans serif"
